WORKDIR /app

# Copy the Python script into the container
COPY simple_time_service.py .

# Set file permissions so that the app can be run by the non-root user
RUN chown -R appuser:appuser /app

# Switch to the non-root user
USER appuser

# Install any required Python packages (if needed)
# If your microservice has external dependencies, uncomment the next line and specify them
# RUN pip install -r requirements.txt

# Expose the port the application will run on
EXPOSE 8080

# Run the application when the container starts
CMD ["python", "SimpleTimeService.py"]